version: '3'

services:
  database:
    build:
      context: .
      dockerfile: ./Dockerfile_bd
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: lab1
      POSTGRES_USER: al
      POSTGRES_PASSWORD: 123

  php_apache:
    build:
      context: .
      dockerfile: ./Dockerfile_php
    ports:
      - "8080:80"
    depends_on:
      - database

  php_websocket:
    build:
      context: .
      dockerfile: ./Dockerfile_web
    ports:
      - "8081:80"
    depends_on:
      - database

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile_enginx
    ports:
      - "80:80"
    volumes:
      - /home/education/rip/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php_apache
      - php_websocket

volumes:
  postgres_data:
