# Используем официальный образ PHP с Apache
FROM php:apache

# Копируем исходный код приложения внутрь контейнера
COPY . /var/www/html

# Устанавливаем необходимые зависимости
RUN apt-get update \
    && apt-get install -y \
        curl \
        git \
    && rm -rf /var/lib/apt/lists/*

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
WORKDIR /var/www/html
EXPOSE 80
CMD ["apache2-foreground"]
