# Используем официальный образ PHP
FROM php:apache

# Копируем исходный код приложения с веб-сокетами
COPY . /var/www/html

# Устанавливаем необходимые зависимости, включая расширения PHP для работы с веб-сокетами
RUN apt-get update \
    && apt-get install -y \
    libssl-dev \
    zlib1g-dev \
    && pecl install -o -f redis \
    && docker-php-ext-enable redis

# Определяем рабочую директорию
WORKDIR /var/www/html

# Открываем порт, на котором будет работать веб-сервер
EXPOSE 80
