version: '3'

services:
  php:
    container_name: php
    build: docker/php
    restart: on-failure
    expose:
      - 9000
    volumes:
      - .:/var/www
    links:
      - db

  chat:
    container_name: chat
    build: docker/php
    restart: on-failure
    ports:
      - 8080:8080
    volumes:
      - .:/var/www
    links:
      - db
    entrypoint: [ "php", "bin/console", "chat" ]

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: on-failure
    ports:
      - 8000:80
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    links:
      - php

  db:
    container_name: db
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: ${DB_DATABASE:-lab1}
      POSTGRES_USER: ${DB_USERNAME:-al}
      POSTGRES_PASSWORD: ${DB_PASSWORD?}
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
